version: '3.1'

services:
  stock_now_pg:
    image: postgres:14.5
    container_name: stock_now_db
    restart: always
    environment:
      POSTGRES_DB: stocknow_db
      POSTGRES_USER: ustock
      POSTGRES_PASSWORD: Rodrig@DB_stock-now!
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5438:5432
